// Generated by tools/build.py.
export const HUB = {
 "name": "MCB 102 Study Hub",
 "short": "MCB 102",
 "slug": "mcb102",
 "mode": "shared-web",
 "focus": {
  "label": "GSI exam focus",
  "short": "GSI",
  "blurb": "What the discussion GSI emphasized, ranked by how likely it is to be on the exam. Start at the top."
 },
 "askName": false
};
